os: windows
script:
- cd packages/ossec-client/3.0.1
- choco pack
- choco install ossec-client.3.0.1.nupkg -y
- choco uninstall ossec-client -y
- cd ../3.1.0
- choco pack
- choco install ossec-client.3.1.0.nupkg -y
- choco uninstall ossec-client -y
language: shell
